src/js/src/components/StoppedExperiment.vue

This PR fixes issue #47.  It ended up being a variable spelling error `tableKey` should be `table.key`

Fixed dropdown listbox cancel bug

---

docker/Dockerfile
docker/docker-compose.yml
docker/minimega/minimega.service
src/go/api/config/default/kali.yml
src/go/api/config/default/minirouter.yml
src/go/api/image/image.go
src/go/cmd/image.go
src/go/tmpl/templates/minirouter/minirouter.init
src/go/tmpl/templates/minirouter/minirouter.service
src/go/tmpl/templates/protonuke/protonuke.init
src/go/tmpl/templates/protonuke/protonuke.service

* Added default image config for Kali
* Updated Dockerfile to include Kali Archive keyring
This commit also includes some updates to image building in general.
* Print deprecation warning for inject_miniccc and inject_protonuke
* Added inject-miniexe subcommand for miniccc, protonuke, and minirouter
* Deprecated inject-miniccc in favor of inject-miniexe
closes #31

Add support for building Kali image

---

src/go/app/startup.go
src/go/internal/mm/minimega.go
src/go/internal/mm/option.go
src/go/types/interfaces/topology.go
src/go/types/version/v0/node.go
src/go/types/version/v1/node.go

This obviously requires that the Windows 10 VM image be configured ahead
of time to run the miniccc agent at boot. Since the `image inject-miniexe`
subcommand uses the startup folder script technique to start the miniccc
agent, the miniccc agent and service must be added to Windows 10 images
in a different manner (e.g. a Packer config).

Enable using minimega C2 on Windows 10 VMs to run startup script

---

src/go/api/experiment/experiment.go
src/go/internal/file/file.go
src/go/internal/file/search.go
src/go/internal/file/types.go
src/go/web/handlers.go
src/go/web/proto/experiment.proto
src/go/web/util/protobuf.go
src/js/src/components/RunningExperiment.vue
src/js/src/components/StoppedExperiment.vue

Added the list of experiment files to a Buefy table to facilitate searching/sorting/paging for the running and stopped experiment views.  This PR satisfies issue #57 .  Here are a few screenshots to give an overview of the searching.  
This screenshot show the list of fields added to the table.  The `Date` column is the default sort column.  Sorting, searching, and pagination is done on the server.  The screenshot also show an example search for files greater than 100 MB using the search term `>= 100 MB`  When searching the file size, the following size abbreviations can be used `KB,MB,GB`.
Here is another screenshot showing a date/time search.   The `Size` and `Date` columns are searched using the following comparison operators `< > = <= >=`.  Currently, in order to search the `Date` …

Search experiment files for running/stopped views

---

.gitignore
src/go/app/ntp.go
src/go/app/vrouter.go
src/go/types/version/v1/network.go
src/go/types/version/v1/schema.go

When minirouter is specified as the os_type for nodes of type Router,
the minimega router commands are used to configure the VM instead of
injecting config files.
Currently supports configuring interface addresses, default gateways,
static routes, and OSPF routing. At some point it will be updated to
also support ACLs via iptables configurations.

Support minirouter as router os_type

---

src/js/src/components/StoppedExperiment.vue

While using GitHub's editor for merge conflict resolution, I deleted something that enabled the multiSelect checkboxes to work.  This fixes the broken multiSelect checkboxes for the stopped view that I broke during merge conflict resolution.

Fix mistake during merge conflict resolution

---

src/go/api/soh/app.go
src/go/api/soh/types.go
src/go/api/soh/util.go
src/go/app/vrouter.go
src/go/internal/mm/c2.go
src/go/internal/mm/minimega.go
src/go/internal/mm/option.go
src/go/types/version/v1/network.go
src/js/src/components/Experiments.vue
src/js/src/components/Hosts.vue
src/js/src/components/RunningExperiment.vue
src/js/src/components/StoppedExperiment.vue
src/js/src/components/Users.vue

Support configuration of TCP and UDP reachability tests in addition to
the ICMP-based reachability testing SoH already supports.
For UDP tests, a valid UDP payload that will trigger a UDP response must
be provided as a Base64-encoded string.
Note that this commit relies on new features recently added to minimega
that haven't been merged into the default minimega branch yet. The
minimega code required is in the activeshadow/minimega@tcp-conn-test
branch.

Add support for custom reachability tests in SoH app

---

docker-build.sh
docker/Dockerfile
src/go/api/soh/app.go
src/go/api/soh/types.go
src/go/api/soh/util.go
src/go/api/vm/vm.go
src/go/app/user.go
src/go/app/vrouter.go
src/go/cmd/root.go
src/go/cmd/ui.go
src/go/internal/common/common.go
src/go/internal/mm/c2.go
src/go/internal/mm/minimega.go
src/go/internal/mm/mm.go
src/go/internal/mm/mmcli/client.go
src/go/internal/mm/option.go
src/go/internal/mm/package.go
src/go/internal/mm/types.go
src/go/tmpl/templates/linux_interfaces.tmpl
src/go/types/version/v1/network.go
src/go/web/handlers.go
src/go/web/log.go
src/js/src/components/Experiments.vue
src/js/src/components/Hosts.vue
src/js/src/components/Log.vue
src/js/src/components/RunningExperiment.vue
src/js/src/components/StateOfHealth.vue
src/js/src/components/StoppedExperiment.vue
src/js/src/components/Users.vue

Users can specify a script to run per host, with the option of comparing
STDOUT or STDERR output from the script to an expected outcome.
This works on both Linux and Windows VMs.

Support custom, host-based user tests via scripts

---

src/go/cmd/ui.go
src/go/web/broker/client.go
src/go/web/option.go
src/go/web/server.go

Use the `--tls-key` and `--tls-cert` options now present for the `phenix ui` subcommand to secure the UI with the provided TLS certificate.

Add support for secure UI

---

src/go/api/vm/vm.go
src/go/cmd/vm.go
src/go/util/printer/printer.go
src/go/web/handlers.go
src/go/web/proto/vm.proto
src/go/web/server.go
src/js/src/components/RunningExperiment.vue

This PR applies to #44.  Functions were added to both the Web UI and command line to enable starting/stopping packet captures via an ipv4 subnet.  
**Current Known Limitations:** Since the minimega capture cli does not currently allow packet captures to be stopped for a specific VM interface, when stopping packet captures for a subnet, all packet captures are stopped for all VMs with an interface in the specified subnet.  This is not the ideal behavior.  An issue has been submitted to the minimega respository https://github.com/sandia-minimega/minimega/issues/1447
**Web UI Examples**
Using the recently merged PR #41 (extended Web UI search), the search bar can be used to specify an ipv4 subnet.  When a valid ipv4 subnet is entered, the `play` button adjacent to the IPv4 label will be …

Added functions to start/stop packet captures via subnet

---

src/go/app/startup.go
src/go/tmpl/templates/startup-scheduler.cmd
src/go/tmpl/templates/windows_startup.tmpl

In an effort to be more consistent across images and to address issues
with using the `Startup` folder in newer versions of Windows to run
scripts at boot, this commit includes backwards-compatible updates to
support a scheduled task in Windows images to run Powershell scripts
present in C:\phenix\startup at boot.
Specifically, this commit updates injections created by the `Startup`
app for Windows VMs to place them in C:\phenix\startup instead of C:\.
It also updates the default Windows Scheduler script that gets placed in
the `Startup` folder to look for the `startup.ps1` script in
C:\phenix\startup.
Additionally, support for an annotation on Windows VMs in the topology
config named `includes-phenix-startup` that, when present, will prevent
the `Startup` app from adding the Windows …

Update startup app and tmpl to account for phenix-startup task in Windows

---

src/go/app/ntp.go
src/go/app/startup.go
src/go/tmpl/templates/ntp_windows.tmpl
src/go/tmpl/templates/phenix-startup.ps1
src/go/tmpl/templates/startup-scheduler.cmd
src/go/tmpl/templates/windows_startup.tmpl

The following is an example of a function other scripts can use to know
if the phenix startup script has fully completed.
```
function Phenix-StartupComplete() {
$key = Get-Item -LiteralPath 'HKLM:\Software\phenix' -ErrorAction SilentlyContinue
if ($key) {
$val = $key.GetValue('startup')
if ($val) {
return $val -eq 'done'
}
return $false
}
return $false
}
```
This commit also updates the scheduled task to run a script that will
execute all PowerShell scripts present in `C:\phenix\startup\*.ps1` on
each boot. This means any scripts placed in this directory must be
idempotent or self-delete.

Update Windows startup process to add a registry entry when done

---

src/go/api/soh/app.go
src/go/api/soh/types.go
src/go/api/soh/util.go
src/go/internal/mm/minimega.go
src/go/internal/mm/option.go
src/go/web/log.go

Added an option to ID clients by hostname, defaulting to false, which
means by default clients will be identified by their UUID when checking
to see if C2 is active for a client.

ID cc clients using UUID by default instead of topology hostname

---

src/go/internal/file/file.go

This fixes the **[UI] Ubuntu 18.04.6 Files Tab Date Column Empty** issue.  The problem was a hardcoded absolute path to the `ls` command.  Since the location of the `ls` command can vary by Linux distribution, the absolute path reference was removed.  The minimega shell command will call `exec.LookPath` to find the absolute path to a command as long as the command is listed in the PATH environment variable.   The screenshot below shows that the issue has been fixed.

Ubuntu18.04.6:Files tab date column populated

---

src/go/web/handlers.go
src/go/web/server.go
src/js/src/components/StoppedExperiment.vue

It will be possible to assign a VLAN ID to a VLAN alias within an existing experiment in the Stopped Component.

Allow for assigning VLAN alias to VLAN ID mappings in UI

---

src/go/tmpl/templates/vmdb.tmpl

This reverts commit 98de05bd00ba23d8c1de986aad1f8311702dd480. This was causing issues with DNS during image build.

Revert "Update vmdb template (#93)"

---

src/go/tmpl/templates/windows_startup.tmpl

In cases where the phenix-startup service is set to run as SYSTEM, the "Restart-Computer" command will fail silently if a user is logged in (e.g., auto login is configured). Adding -Force bypasses this, and capturing any error output helps debugging.

Add -Force to 'Restart-Computer' and log errors

---

docker/Dockerfile

Swap gzip with pigz to allow for parallelized compression of ramdisk. Add pigz as apt dependency in phenix image.

Update vmdb2 version. Add pigz apt dependency for phenix image.

---

src/go/api/image/constants.go
src/go/api/image/image.go

Fixes #105 
Tested with
`phenix image create -r kali -v mingui -f qcow2 kali`
and
`phenix image create -v mingui -f qcow2 mingui`
__*Note: `mingui` for Ubuntu only works with the default release (bionic)*__

Separate out kali GUI packages.

---

src/go/api/vm/vm.go

The minimega base directory was hardcoded in the `CommitToDisk` function which would cause the UI `Create Backing Image` to fail when the user specifies the `--base-dir.minimega` option on the command line.

CommitToDisk:Remove hardcoded minimega base directory

---

src/js/src/components/RunningExperiment.vue
src/js/src/components/StoppedExperiment.vue

The subnet captures buttons adjacent to the IPv4 label disappeared from the RunningExperiment view.  Apparently, turning the buttons into Buefy buttons fixed the issue.  The references to the lodash debounce function were also fixed for both the Running and Stopped experiment views.

Fixed subnet capture buttons

---

docker/Dockerfile

Commit e0678ad included moving the installation of our custom version of vmdb2 to the final Docker image target in docker/Dockerfile. We needed to use the -O option instead of the -P option to make sure the existing vmdb2 installed via apt (to pull in the required dependency packages) was truly overwritten.
fixes #137

fix: correctly install custom version of vmdb2

---

docker/Dockerfile
src/go/api/vm/vm.go

Recent(ish) updates to qemu-img now require specification of image formats. This became an issue when the base Docker image was upgraded to 22.04 in e0678ad.

fix: specify src and dst image formats when rebasing new backing image

---

src/go/tmpl/templates/windows_startup.tmpl

Adds a wait loop in the windows startup script if this annotation is added:
```yaml
annotations:
phenix/domain-controller: "true"
```
The wait loop specifically waits for the `Get-ADDomain` command to return, meaning the machine has fully booted and active directory services have started. Without this delay, the DC machine may enter a reboot loop.

feat: Add a startup script delay to annotated domain controllers

---

src/go/util/mm/minimega.go

This fixes a Phenix VM list web page loading error that occurs when a disk image only exists on a remote node.  This is the case when doing a VM snapshot for a VM that exists on a remote node. The minimega `disk info` command which wraps `qemu-img` info is ran on the local node and does not appear to account for disk images on remote nodes.

GetVMInfo:Disk info for VMs on remote nodes

---

src/go/api/experiment/experiment.go
src/go/api/experiment/option.go
src/go/app/app.go
src/go/cmd/experiment.go
src/go/types/interfaces/scenario.go
src/go/types/scenario.go
src/go/types/version/v2/scenario.go
src/go/web/handlers.go
src/go/web/proto/experiment.proto
src/js/src/components/Experiments.vue

This PR allows a user to disable applications from a scenario when creating an experiment. Instead of having to create a separate scenario file and go through the process of setting up phenix again, the user can live-make a custom scenario that is a subset of an existing scenario. The tags that appear when a user selects a scenario on the 'create an new experiment' window can be toggled to disable / enable apps. 
Changes:
- js
- Make application tags colored + toggle on / off
- Send list of enabled apps to back end when creating experiment
- go
- Experiment options has list of enabled apps 
- When creating experiment, loop over all 'enabled' applications and add from base scenario applications
TODO:
- change color scheme for enabled / disabled tags. The disabled color is the current …

Disable scenario apps during experiment creation

---

.github/workflows/docker.yml
.gitignore
README.md
docker/Dockerfile

The primary reason for this PR is to allow usage of non-GitHub repos to be used for `APPS_REPO` during the Docker image build. There are also a number of other enhancements to the Dockerfile and a handful of updates to the README (just some cleanup while I was in the area).
- APPS_REPO must now include the base domain for the repo. By default, this is github.com. The change should have minimal impact on existing workflows. This change enables use of other Git hosts for phenix-apps.
- Add some labels to the image metadata.
This is a best practice that we use for several other projects.
- Disable pip update checks
- Disable pip caching
- Move scorch dependency installs before python installs, to improve caching (since these usually don't change, so docker buildkit can cache and not have to …

Changes to Docker build to improve dev workflows

---

src/go/api/cluster/files.go
src/go/api/vm/vm.go
src/go/util/file.go
src/go/util/mm/minimega.go
src/go/util/mm/types.go
src/go/web/handlers.go
src/go/web/proto/vm.proto
src/go/web/server.go
src/go/web/util/protobuf.go
src/js/src/components/RunningExperiment.vue

Removed the unused `record screenshots` button from the experiment modal in the RunningExperiments view and replaced it with an `insert optical disc` function.  While inserting a disc in the drive of a running VM is fairly straightforward using the minimega command line, being able to insert a disc from the UI is a bit easier and convenient.
The screenshots below show the placement of the `insert optical disc` function/button.  
**Insert Optical Disc button replaces `record screenshots` button**
**Only ISOs appear in the dropdown**

[UI Feature] Change optical disc from VM modal

---

src/js/src/components/Experiments.vue

Adding a null check before creating disabledApps list. Create window works with and without a scenario selected. 
@activeshadow Not sure how to link this pull request with the issue -- this will resolve issue #158

fix(ui): allow experiment to be created without a scenario

---

.github/workflows/docker.yml
.github/workflows/minimega.yml
docker/Dockerfile
docker/docker-compose.yml
src/go/web/public/novnc/core/rfb.js
src/go/web/public/vnc.html

This is a minor update that coincides with a minimega PR adding copy/paste support: https://github.com/sandia-minimega/minimega/pull/1520
This disables noVNC from using the [extended clipboard pseudo encoding](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extended-clipboard-pseudo-encoding). Minimega uses a passive shim to read RFB messages, and can't support the extended clipboard.

Disable extended clipboard in noVNC

---

src/go/util/mm/minimega.go
src/go/util/mm/mmcli/tabular.go

When `cc tunnel` is run in a namespace that has multiple nodes, each node will try to create the tunnel and only one will succeed since the VM being used for the tunnel will only be on one node. The other nodes will report back an error, and this was causing phēnix to assume the tunnel creation had failed.
This commit updates the `cc tunnel` command to be prefixed with the node to execute the command on rather than having it sprayed to all nodes.

fix: avoid tunnel failures from expected errors

---

src/go/util/mm/minimega.go
src/go/util/mm/types.go
src/js/src/components/Hosts.vue

Add disk space % to Hosts tab in phenix UI - uses `df` on `common.PhenixBase` and `common.MinimegaBase`.

feat: add disk space to hosts tab in phenix ui

---

src/go/api/scorch/app.go

Currently, scorch archive and info files are created using the start time in RFC3339 format, which includes colons. This causes issues with some OSes, where colons in filenames are not expected (ex. running `tar xzfv scorch-run-1_2024-07-03T23:02:41Z.tgz` will throw an error on linux systems).
All Golang [time.Format](https://go.dev/src/time/format.go) pre-defined layouts that include times also include colons, so this fix uses a custom format `2006-01-02T15-04-05Z0700`.
Alternatively `strings.ReplaceAll(startTime.Format(time.RFC3339, ":", "=")` could be used.

fix: remove colons from filenames output by scorch

---

src/go/api/scorch/app.go

This adds some simple logging to scorch pipelines. Please feel free to suggest edits.
example with INF / DBG / ERROR

Feat: add more logging to scorch

---

src/go/api/scorch/app.go
src/go/app/vrouter.go
src/go/tmpl/templates/vyatta.tmpl

For vrouter, allow `proto: dhcp` in the topology interface definition. Also spelling fix.

Allow dhcp proto for vrouter interfaces.

---

src/go/cmd/ui.go
src/go/web/option.go
src/go/web/server.go

Adds an optional (and hidden) flag for specifying a group ID to apply group ownership to the unix-socket. Also sets the permissions to be group-writable. Use case: phenix starts from within a docker container as the `root` user, but normal users wish to be able to use the unix-socket to communicate with phenix (without having to switch to `root`). This allows the users to be a part of the group specified in the flag and have write access to the socket.
Normal (`--unix-socket-gid=1000`):
Error (`--unix-socket-gid=foobar`):

Add optional --unix-socket-gid flag

---

docker/Dockerfile.minimega
src/go/api/experiment/experiment.go

Commit 7b80f40 incorrectly assumed users would always want to use the GRE mesh namespace bridge capability in minimega when the default bridge for an experiment was not `phenix` (the default).

fix: don't automatically use GRE mesh when bridge name isn't phenix

---

src/js/src/components/RunningExperiment.vue
src/js/src/components/StoppedExperiment.vue

In the StoppedExperiment view, if there are no qcow images (i.e. .qcow2, .qc2) in the minimega files directory (usually `/phenix/images`), then the waiting indicator would spin indefinitely.  Likewise, in the RunningExperiment view, when using the `ChangeOpticalDisc` feature, the waiting indicator would spin indefinitely if there were no ISOs in the minimega files directory.  This patch fixes the issue with the infinite waiting indicator.

[UI] Fix infinite waiting when updating disks

---

src/go/app/startup.go
src/go/tmpl/templates/linux_domain.tmpl

This adds the ability for linux hosts to join MS Active Directory domains using realmd (assumed to be already installed).
Some light refactoring of when we check for the startup app to do it once before all hosts, now that it is needed for both linux and windows boxes.

feat: extend startup join domain to linux

---

src/go/api/soh/soh.go
src/go/api/soh/types.go
src/go/api/vm/option.go
src/go/api/vm/vm.go
src/go/tmpl/templates/minimega_script.tmpl
src/go/tmpl/tmpl.go
src/go/types/interfaces/topology.go
src/go/types/version/v0/node.go
src/go/types/version/v1/node.go
src/go/util/mm/minimega.go
src/go/util/mm/mm.go
src/go/util/mm/option.go
src/go/util/mm/package.go
src/go/util/mm/types.go
src/go/web/handlers.go
src/go/web/proto/vm.proto
src/js/src/components/RunningExperiment.vue
src/js/src/components/StateOfHealth.vue
src/js/src/components/StoppedExperiment.vue
src/js/src/components/VMLabelsModal.vue
src/js/src/main.js

This adds a few features in the UI for making notes and customizing the way a VM appears in the SOH graph. The intent is to make it easier for users to track/manage the status of VMs within an experiment (e.g., a user may mark a node red and add a note "reached by red team")
* Adds a new modal for viewing/editing the labels of a VM
* Separate "notes" section that allows multiline, maintains insertion order, and hides key
* Available in experiment pages and SOH
* Treats minimega tags and phenix labels as one (meaning persistent across experiment runs, and also available in mm cli)
* Changes SOH details modal to show notes at the top
* Adds buttons to edit labels and override style
* New style modal lets user override the fill color, stroke color, and stroke style of a node. This takes …

User Annotation Improvements

---

.github/workflows/docker.yml
.github/workflows/minimega.yml
docker/Dockerfile
docker/docker-compose.yml
src/go/tmpl/templates/minimega_script.tmpl
src/go/types/interfaces/topology.go
src/go/types/version/v0/node.go
src/go/types/version/v1/node.go

Supports adding a keyword to the src field of a file injection to delete the file/directory in a disk image. E.g.
```yml
injections:
- src: TERMINATED
dst: /ProgramData/Microsoft/Windows Defender
```
Depends on https://github.com/sandia-minimega/minimega/pull/1548

feat: support deleting files in disk injects

---

src/go/api/config/default/caldera.yml

* bump Caldera version
* pre-install Caldera UI dependencies and build UI
* pre-install additional plugin packages
The last two bullets above help to speed up Caldera server start times, as well as operating as expected when there is no tap allowing internet access for an experiment (normally the UI and plugin dependencies are installed in real-time when the server is started).

fix: Caldera image config updates to improve offline use

---

src/go/web/vnc.go

Adds ability to disable banners for a specific VM using the existing VNC banner annotation via a newly added disabled setting. Note that this will disable both the top and bottom banner.
```
annotations:
vncBanner:
disabled: true
```

feat: support disabling of VNC banners for VMs

---

src/go/web/server.go
src/js/src/App.vue
src/js/src/components/Configs.vue
src/js/src/components/Experiments.vue
src/js/src/components/Footer.vue
src/js/src/components/Header.vue
src/js/src/components/Hosts.vue
src/js/src/components/Log.vue
src/js/src/components/MiniConsole.vue
src/js/src/components/RunningExperiment.vue
src/js/src/components/Scorch.vue
src/js/src/components/StoppedExperiment.vue
src/js/src/components/Tunneler.vue
src/js/src/components/VMtiles.vue

* make header and footer span entire width
* move logo into header; use buefy navbar for better responsiveness
* make content area wider - wider max and full-width at smaller resolutions
* remove <hr> for each route view
* update buefy to 0.9.29
* remove most fixed width table columns
* tables were breaking after buefy update
* update copyright year in footer
* fix apps list overflowing in experiment view
* load favicon in https
* prevent trying to connect to websocket on login/signup pages
New feature
Screenshot shows most of the changes (navbar, experiments header)

feat(ui): general ui improvements

---

.github/workflows/docker.yml
.github/workflows/minimega.yml
docker/Dockerfile
docker/Dockerfile.minimega
docker/docker-compose.yml
docker/jit/Dockerfile
podman/pod.yml

* update mm rev to `6cf6cfb` to support disk changes
* change mm ref to main repo rather than a fork
* fix gh actions failing if branch had a '/' by using docker meta action to build tag names 
* additional fixes to jit image following tag fix
Follow on to PR #209 
Bugfix
Did basic testing to verify images built and that disks page worked as expected

fix: update mm refs in docker and gh actions

---

src/go/api/config/config.go
src/go/api/config/config_test.go
src/go/api/config/option.go
src/go/store/types.go
src/go/util/common/common.go
src/go/web/workflow.go

This PR adds support for using environment variables in phenix configs (YAML or JSON).
> [!WARNING]
> This change also converts the old `{{BRANCH_NAME}}` scoped variable for the [phenix workflow](https://github.com/sandialabs/sceptre-phenix?tab=readme-ov-file#git-workflow-support) to an environment variable `${BRANCH_NAME}`. The phenix workflow api calls and scripts remain unchanged, as the code handles passing the uri argument as an environment variable to the new config code. The only change that's required as part of this PR is that any reference to `{{BRANCH_NAME}}` should be changed to `${BRANCH_NAME}`
n/a
On creation of a new phenix config, this code replaces any environment variable placeholders found in the config with …

feat: parse env vars in phenix configs

---

src/go/cmd/root.go

Currently if the user is sudo, phenix tries to get the actual user through `user.Lookup`. It panics if that lookup returns nil; however, the function returns nil for LDAP users. As a result, phenix may unnecessarily panic in certain setups making it unusable.
The lookup is only used to look for a config file in the user's home directory, so this change just reverts to using the sudo user for this lookup.

fix: don't panic if user is sudo and actual user is not present

---

src/go/api/soh/app.go
src/go/api/soh/types.go
src/go/api/soh/util.go

One new feature and several fixes for SoH:
* **feat: `startupDelay`** (I am open to name changes) is a parameter that can be specified in order to delay SoH checks from running immediately at experiment start (or whenever the SoH app is reached). In every case that I have used SoH, I have found that it's first run in the experiment PostStart phase _always_ fails. This is due to various things, but basically "the experiment is still starting up, not all checks are going to work, yet".  This leads to a workflow of: start an experiment, wait for SoH to run in the PostStart phase (and fail), then manually run again either through the UI or CLI in order to get a "good" SoH check. Adding this delay allows slower configurations and processes to finish before SoH actually kicks off its checks, …

feat: SoH startupDelay, fix: SoH empty address, ns path

---

docker/Dockerfile

Add `guestfish` apt package to the phenix Docker image. [guestfish](https://libguestfs.org/guestfish.1.html) is a tool for examining and modifying VM filesystems. This is required by some internal tooling, and it would be helpful to have it installed in upstream. 
The change in image size should be relatively minimal, and besides, the image doesn't get pulled that often 🤠 
N/A
Please provide any additional information or context for your pull request here.

build: add guestfish to phenix image

---

src/js/src/components/StateOfHealth.vue

Removes the unreachable SoH Messages tab
ref: https://github.com/sandialabs/sceptre-phenix/issues/235
#235
Docs updated [sandialabs/sceptre-phenix-docs/#18](https://github.com/sandialabs/sceptre-phenix-docs/pull/18)

fix: remove dead SoH Messages tab
